[package]
name = "rust-wav2mp3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#add lameMP3 rust binding dependency

lame-sys = "0.1"
num_cpus = "1.13.0"

libc = "0.2.0"
